# Support vector regressor implementation (SVR)

In [2]:
import pandas as pd 
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [5]:
from sklearn.datasets import make_regression

X , y = make_regression(n_samples=1000, n_features=2, n_targets=1 , noise = 3.0)

In [7]:
print(X , y)

[[-0.52171224 -0.69724818]
 [ 0.70781959 -0.1882406 ]
 [-0.17058082 -0.84969835]
 ...
 [ 0.66781231 -0.48635777]
 [-0.51168013  0.56126825]
 [-1.90549045  1.60174536]] [-4.42482250e+01  3.03109898e+01 -3.05199122e+01  2.22917966e+01
  1.59744339e+00  7.89013092e+01 -5.24457098e+01 -1.94257062e+01
  3.03774777e+01 -8.65703771e+01  1.80010520e+01  7.32406679e+01
 -3.27716805e+00 -9.93419667e+01 -1.56347946e+02 -5.98656183e+01
  5.67134173e+01 -1.13819982e+02  2.69763528e+01  1.13700659e+02
  5.38297115e+01 -1.95311883e+01 -9.50413000e+01  1.00971762e+01
 -3.04904917e+01 -2.44421775e+01  4.68470212e+01  6.02684832e+01
  1.04133797e+02 -1.41676805e+01 -4.99299868e+01  6.72800912e-01
 -1.29031203e+02 -3.60967845e+01 -1.01062304e+02 -6.06643872e+01
  4.20931483e+01  5.38362494e+01 -3.73188659e+01 -9.12256540e+01
  4.60833201e+01  1.43758291e+02 -1.75383208e+01 -1.32983264e+02
 -1.95669823e+01 -1.31130404e+00  1.58996925e+01  6.70310364e+01
 -3.70085205e+01  5.44618403e+01  2.35959764e+01 -1.

In [12]:
pd.DataFrame(X)[0]

0     -0.521712
1      0.707820
2     -0.170581
3      0.682755
4     -0.089363
         ...   
995    0.710762
996   -0.549917
997    0.667812
998   -0.511680
999   -1.905490
Name: 0, Length: 1000, dtype: float64

In [13]:
pd.DataFrame(X)[1]

0     -0.697248
1     -0.188241
2     -0.849698
3     -0.491091
4      0.434083
         ...   
995   -0.002816
996    1.240799
997   -0.486358
998    0.561268
999    1.601745
Name: 1, Length: 1000, dtype: float64

In [ ]:
sns.scatterplot(x=pd.DataFrame(X)[0] , y=pd.DataFrame(X)[1], hue = y)

In [15]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X , y , test_size = 0.3 , random_state = 0)

In [16]:
X_train.shape , X_test.shape

((700, 2), (300, 2))

In [18]:
y_train.shape , y_test.shape

((700,), (300,))

In [33]:
from sklearn.svm import SVR

model = SVR(kernel='linear')

In [34]:
model.fit(X_train, y_train)

SVR(kernel='linear')

In [36]:
model.coef_

array([[52.82975393, 25.59866582]])

In [37]:
y_pred = model.predict(X_test)
y_pred

array([-1.20246282e+02,  5.69805054e+01, -1.15694707e+01,  8.81159904e+01,
       -2.27160608e+01,  3.59553840e+00,  6.26314754e+01, -5.78568486e+00,
       -1.74018853e+00,  2.59476263e+01, -5.14677167e+01, -8.14380238e+00,
       -1.00073762e+02, -1.06345557e+01,  1.77539504e+01, -2.04394868e+01,
        3.32489046e+01,  2.04003149e+01, -1.54279913e+02, -3.61411689e+01,
       -6.00599196e-01,  7.88242109e+01, -1.49476543e+01, -1.00171901e+01,
       -4.13560753e+01,  4.61138006e+01, -2.75956511e+00,  1.39459024e+01,
       -1.03494535e+02,  3.25635304e+01, -6.00253311e+01, -3.63335040e+01,
       -1.85019780e+01, -6.90441827e+01,  2.32553807e+01, -7.88764940e+01,
        2.10552524e+00, -3.28694382e+01, -1.63895023e+01,  2.94054452e+01,
       -1.19341466e+02,  2.69913840e+00,  4.68354893e+01,  1.59199089e+00,
        4.43697889e+01, -4.04112869e+00, -2.58878422e+01,  4.62952665e+01,
       -3.08691272e+01, -2.00250419e+01, -2.16067826e+00, -2.93987923e+01,
        3.50978329e+01,  

# sklearn.metrics

In [39]:
from sklearn.metrics import r2_score

print(r2_score(y_test , y_pred)*100)

99.7356859020375


# Hyperparamter Tuning with SVC

In [47]:
from sklearn.model_selection import GridSearchCV

# Define the model
model = SVR()

# Define the parameter grid
param_grid = {
    'C': [0.1, 1, 10, 100],
    'gamma': [1e-3, 1e-4, 'scale', 'auto'],
    'kernel': ['linear', 'poly', 'rbf', 'sigmoid']
}


GridSearch = GridSearchCV( model, param_grid, cv=5)

GridSearch

GridSearchCV(cv=5, estimator=SVR(),
             param_grid={'C': [0.1, 1, 10, 100],
                         'gamma': [0.001, 0.0001, 'scale', 'auto'],
                         'kernel': ['linear', 'poly', 'rbf', 'sigmoid']})

In [48]:
GridSearch.fit(X_train, y_train)

GridSearchCV(cv=5, estimator=SVR(),
             param_grid={'C': [0.1, 1, 10, 100],
                         'gamma': [0.001, 0.0001, 'scale', 'auto'],
                         'kernel': ['linear', 'poly', 'rbf', 'sigmoid']})

In [49]:
GridSearch.best_params_

{'C': 10, 'gamma': 0.001, 'kernel': 'linear'}

In [52]:
best_model = GridSearch.best_estimator_
best_model

SVR(C=10, gamma=0.001, kernel='linear')

In [54]:
best_y_pred = best_model.predict(X_test)
best_y_pred

array([-1.20792665e+02,  5.73252147e+01, -1.15892783e+01,  8.85714765e+01,
       -2.27767429e+01,  3.65847813e+00,  6.30115214e+01, -5.77208073e+00,
       -1.72501026e+00,  2.61286671e+01, -5.16801861e+01, -8.16047969e+00,
       -1.00510795e+02, -1.06470875e+01,  1.79133998e+01, -2.05168262e+01,
        3.34583370e+01,  2.05448806e+01, -1.55040272e+02, -3.62809437e+01,
       -5.81103648e-01,  7.92318193e+01, -1.49642704e+01, -9.98484553e+00,
       -4.14864237e+01,  4.63770798e+01, -2.72289439e+00,  1.40649926e+01,
       -1.03958836e+02,  3.27831999e+01, -6.02821869e+01, -3.64536916e+01,
       -1.85518475e+01, -6.93367686e+01,  2.34016815e+01, -7.91957649e+01,
        2.17216383e+00, -3.29766162e+01, -1.64682363e+01,  2.96099530e+01,
       -1.19897463e+02,  2.73392733e+00,  4.71204039e+01,  1.68714554e+00,
        4.46262115e+01, -4.00065402e+00, -2.59687238e+01,  4.65689844e+01,
       -3.09694189e+01, -2.00398011e+01, -2.14171010e+00, -2.94854704e+01,
        3.53320538e+01,  

In [57]:
from sklearn.metrics import r2_score

print(r2_score(y_test , best_y_pred)*100)

99.73688488716148
