# Data Encoding & Nominal Encodeing

***Daa encoding refer& o he process of convering caegorical or qualiaive daa ino a numerical forma
ha can be ea&ily proce&&ed by machine learning algorihm&r***

# Types of Data in Machine Learning

***Categorical Data vs. Numerical Data***


***>> Define caegorical data as variables ha can take on a limited and fixed number of values or caegoriesr***

***>> Define numerical data as variables that represen measurable quantities and can take on a range of
valuesr***

# Nominal /  One-Hot Encoding

In [4]:
pip install -U scikit-learn


[notice] A new release of pip available: 22.2.2 -> 24.0
[notice] To update, run: python.exe -m pip install --upgrade pip


In [5]:
import pandas as pd
from sklearn.preprocessing import OneHotEncoder

C:\Users\mdaza\AppData\Local\Temp\ipykernel_9568\1160900076.py:1: DeprecationWarning: 
Pyarrow will become a required dependency of pandas in the next major release of pandas (pandas 3.0),
(to allow more performant data types, such as the Arrow string type, and better interoperability with other libraries)
but was not found to be installed on your system.
If this would cause problems for you,
please provide us feedback at https://github.com/pandas-dev/pandas/issues/54466
        
  import pandas as pd


In [6]:
df = pd.DataFrame({'Status' : ['single' , 'married' , 'separated', 'single' , 'married' , 'separated' , 'separated']})

df

Status
0     single
1    married
2  separated
3     single
4    married
5  separated
6  separated

In [7]:
encoder = OneHotEncoder()
encoder

OneHotEncoder()

In [8]:
df_encoder = encoder.fit_transform(df[['Status']]).toarray()

In [9]:
encoder.get_feature_names_out()

array(['Status_married', 'Status_separated', 'Status_single'],
      dtype=object)

In [10]:
encoded_data = pd.DataFrame(df_encoder , columns = encoder.get_feature_names_out())

In [11]:
encoder.transform([['single']]).toarray()

c:\Users\mdaza\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(


array([[0., 0., 1.]])

# Practical Implementation in Datasets

In [12]:
pd.concat([df , encoded_data] , axis=1)

Status  Status_married  Status_separated  Status_single
0     single             0.0               0.0            1.0
1    married             1.0               0.0            0.0
2  separated             0.0               1.0            0.0
3     single             0.0               0.0            1.0
4    married             1.0               0.0            0.0
5  separated             0.0               1.0            0.0
6  separated             0.0               1.0            0.0

In [13]:
import seaborn as sns

data = sns.load_dataset("tips")

In [14]:
encoders = OneHotEncoder()
encodered = encoders.fit_transform(data[['sex' , 'smoker' , 'time']]).toarray()

In [15]:
df_encoded = pd.DataFrame(encodered , columns = encoders.get_feature_names_out())

In [16]:
pd.concat([data , df_encoded] , axis=1)

total_bill   tip     sex smoker   day    time  size  sex_Female  \
0         16.99  1.01  Female     No   Sun  Dinner     2         1.0   
1         10.34  1.66    Male     No   Sun  Dinner     3         0.0   
2         21.01  3.50    Male     No   Sun  Dinner     3         0.0   
3         23.68  3.31    Male     No   Sun  Dinner     2         0.0   
4         24.59  3.61  Female     No   Sun  Dinner     4         1.0   
..          ...   ...     ...    ...   ...     ...   ...         ...   
239       29.03  5.92    Male     No   Sat  Dinner     3         0.0   
240       27.18  2.00  Female    Yes   Sat  Dinner     2         1.0   
241       22.67  2.00    Male    Yes   Sat  Dinner     2         0.0   
242       17.82  1.75    Male     No   Sat  Dinner     2         0.0   
243       18.78  3.00  Female     No  Thur  Dinner     2         1.0   

     sex_Male  smoker_No  smoker_Yes  time_Dinner  time_Lunch  
0         0.0        1.0         0.0          1.0         0.0  
1         1.0        1.0         0.0          1.0         0.0  
2         1.0        1.0         0.0          1.0         0.0  
3         1.0        1.0         0.0          1.0         0.0  
4         0.0        1.0         0.0          1.0         0.0  
..        ...        ...         ...          ...         ...  
239       1.0        1.0         0.0          1.0         0.0  
240       0.0        0.0         1.0          1.0         0.0  
241       1.0        0.0         1.0          1.0         0.0  
242       1.0        1.0         0.0          1.0         0.0  
243       0.0        1.0         0.0          1.0         0.0  

[244 rows x 13 columns]

# Label Encoding

In [17]:
from sklearn.preprocessing import LabelEncoder

In [18]:
label_encoder = LabelEncoder()

label_encoder.fit_transform(df[['Status']])

c:\Users\mdaza\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\preprocessing\_label.py:114: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


array([2, 0, 1, 2, 0, 1, 1])

In [19]:
label_encoder.transform([['single']])

c:\Users\mdaza\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\preprocessing\_label.py:132: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, dtype=self.classes_.dtype, warn=True)


array([2])

# Ordinal Encoder

In [20]:
from sklearn.preprocessing import OrdinalEncoder

In [24]:
df = pd.DataFrame({'class' : ['HS' , 'INTER' , 'GR' , 'PG' , 'PhD ', 'INTER' , 'GR' , 'PG' , 'PhD ']})


df



class
0     HS
1  INTER
2     GR
3     PG
4   PhD 
5  INTER
6     GR
7     PG
8   PhD

In [26]:
encoder = OrdinalEncoder(categories=[['HS' , 'INTER' , 'GR' , 'PG' , 'PhD ']])
encoder.fit_transform(df[['class']])

array([[0.],
       [1.],
       [2.],
       [3.],
       [4.],
       [1.],
       [2.],
       [3.],
       [4.]])

# target guided ordinal encoding

***replace by mean , median***

In [28]:
data = sns.load_dataset("tips")
data

total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

In [31]:
mean_bill = data.groupby('time')['total_bill'].mean().to_dict()

mean_bill

C:\Users\mdaza\AppData\Local\Temp\ipykernel_9568\2413858811.py:1: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  mean_bill = data.groupby('time')['total_bill'].mean().to_dict()


{'Lunch': 17.168676470588235, 'Dinner': 20.79715909090909}

In [34]:
data['time_encoded'] = data['time'].map(mean_bill)

data

total_bill   tip     sex smoker   day    time  size time_encoded
0         16.99  1.01  Female     No   Sun  Dinner     2    20.797159
1         10.34  1.66    Male     No   Sun  Dinner     3    20.797159
2         21.01  3.50    Male     No   Sun  Dinner     3    20.797159
3         23.68  3.31    Male     No   Sun  Dinner     2    20.797159
4         24.59  3.61  Female     No   Sun  Dinner     4    20.797159
..          ...   ...     ...    ...   ...     ...   ...          ...
239       29.03  5.92    Male     No   Sat  Dinner     3    20.797159
240       27.18  2.00  Female    Yes   Sat  Dinner     2    20.797159
241       22.67  2.00    Male    Yes   Sat  Dinner     2    20.797159
242       17.82  1.75    Male     No   Sat  Dinner     2    20.797159
243       18.78  3.00  Female     No  Thur  Dinner     2    20.797159

[244 rows x 8 columns]