# Model Training Pipline and ColumnTransformer

In [26]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [27]:
data = sns.load_dataset('tips')
data.head()

total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

***predict whats the time? if its Lunch or dinner***

In [28]:
# predict whats the time? if its Lunch or dinner >> time is the target variables

data.time.unique()

['Dinner', 'Lunch']
Categories (2, object): ['Lunch', 'Dinner']

***EDA >> Subjective***

***endcoding , missing value treaiment , scaling >> automate***

In [29]:
# EDA >> Subjective
#  endcoding , missing value treaiment , scaling >> automate 

data.info() 

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 244 entries, 0 to 243
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype   
---  ------      --------------  -----   
 0   total_bill  244 non-null    float64 
 1   tip         244 non-null    float64 
 2   sex         244 non-null    category
 3   smoker      244 non-null    category
 4   day         244 non-null    category
 5   time        244 non-null    category
 6   size        244 non-null    int64   
dtypes: category(4), float64(2), int64(1)
memory usage: 7.4 KB


# Label Encoder

In [30]:
from sklearn.preprocessing import LabelEncoder

Encoder = LabelEncoder()
data['time'] = Encoder.fit_transform(data['time'])

In [31]:
data.head()

total_bill   tip     sex smoker  day  time  size
0       16.99  1.01  Female     No  Sun     0     2
1       10.34  1.66    Male     No  Sun     0     3
2       21.01  3.50    Male     No  Sun     0     3
3       23.68  3.31    Male     No  Sun     0     2
4       24.59  3.61  Female     No  Sun     0     4

In [32]:
data.time.unique()  # lunch = 0 , Dinner = 1

array([0, 1])

In [33]:
X = data.drop('time' , axis=1 )
y = data['time']

In [34]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X , y , test_size = 0.3 , random_state = 0)

In [35]:
X_train.head()

total_bill   tip     sex smoker   day  size
61        13.81  2.00    Male    Yes   Sat     2
146       18.64  1.36  Female     No  Thur     3
52        34.81  5.20  Female     No   Sun     4
66        16.45  2.47  Female     No   Sat     2
26        13.37  2.00    Male     No   Sat     2

In [36]:
data.isna().sum()

total_bill    0
tip           0
sex           0
smoker        0
day           0
time          0
size          0
dtype: int64

In [37]:
# Handling the missing values in the dataset
# data encoding
# feature scaling

from sklearn.impute import SimpleImputer # for missing values

from sklearn.preprocessing import OneHotEncoder # for encoding

from sklearn.preprocessing import StandardScaler # for scaling

***Pipeline***

***ColumnTransformer***

In [38]:
from sklearn.pipeline import Pipeline  # A pipeline is a sequence of steps

from sklearn.compose import ColumnTransformer # group all the pipeline step for each of column

In [39]:
cat_column = ['sex' , 'smoker' , 'day'] 

num_column = ['total_bill' , 'tip' , 'size']

In [40]:
# feature engineering automation using pipeline and columntransformer

# Define numerical pipeline
num_pipeline = Pipeline(steps=[
    ('imputation', SimpleImputer(strategy='median')),
    ('standardization', StandardScaler())
])

# Define categorical pipeline
col_pipeline = Pipeline(steps=[
    ('imputation', SimpleImputer(strategy='most_frequent')),
    ('encoding', OneHotEncoder())
])

In [41]:
from sklearn.compose import ColumnTransformer
perprocessor = ColumnTransformer([("num_pipeline" , num_pipeline , num_column ) ,
                                  ("col_pipeline", col_pipeline, cat_column)
])

In [42]:
X_train = perprocessor.fit_transform(X_train)

X_test = perprocessor.transform(X_test)

In [43]:
X_train

array([[-0.68232142, -0.68502117, -0.6164355 , ...,  1.        ,
         0.        ,  0.        ],
       [-0.15257538, -1.13966829,  0.46391538, ...,  0.        ,
         0.        ,  1.        ],
       [ 1.62092224,  1.58821446,  1.54426626, ...,  0.        ,
         1.        ,  0.        ],
       ...,
       [-1.02890475, -1.04021424, -0.6164355 , ...,  0.        ,
         0.        ,  1.        ],
       [ 1.35659761,  2.15652336,  1.54426626, ...,  0.        ,
         1.        ,  0.        ],
       [-1.40181086,  1.55269515, -0.6164355 , ...,  0.        ,
         1.        ,  0.        ]])

In [44]:
X_test

array([[-0.26773756, -0.23037404,  0.46391538,  0.        ,  1.        ,
         1.        ,  0.        ,  0.        ,  1.        ,  0.        ,
         0.        ],
       [-0.19096277,  0.56525842,  1.54426626,  0.        ,  1.        ,
         0.        ,  1.        ,  0.        ,  1.        ,  0.        ,
         0.        ],
       [-0.05934885,  0.38766189, -0.6164355 ,  0.        ,  1.        ,
         1.        ,  0.        ,  0.        ,  0.        ,  1.        ,
         0.        ],
       [-1.40181086, -1.3954073 , -1.69678639,  1.        ,  0.        ,
         1.        ,  0.        ,  0.        ,  1.        ,  0.        ,
         0.        ],
       [-0.41251287, -0.3298281 , -0.6164355 ,  1.        ,  0.        ,
         0.        ,  1.        ,  1.        ,  0.        ,  0.        ,
         0.        ],
       [-1.56632827, -1.3954073 , -0.6164355 ,  1.        ,  0.        ,
         0.        ,  1.        ,  1.        ,  0.        ,  0.        ,
         0.   

In [67]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC

In [68]:
# Sample dictionary of models
models = {
    'RandomForest': RandomForestClassifier(),
    'LogisticRegression': LogisticRegression(),
    'SVM': SVC()
}


In [69]:
from sklearn.metrics import accuracy_score

def model_train_eval(X_train, y_train, X_test, y_test, models):
    evaluation = {}
    for name, model in models.items():
        model.fit(X_train, y_train)
        y_pred = model.predict(X_test)
        model_score = accuracy_score(y_test, y_pred)
        evaluation[name] = model_score
    return evaluation


   

In [70]:
# Assume X_train, y_train, X_test, y_test are predefined
evaluation_results = model_train_eval(X_train, y_train, X_test, y_test, models)

# Print evaluation results
for model_name, accuracy in evaluation_results.items():
    print(f"{model_name}: {accuracy:.4f}")

RandomForest: 0.9054
LogisticRegression: 0.9189
SVM: 0.9189
